### ISSUE TITLE
Blockstor perf test script fails in cleanup

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-rest-api#256]
```
INFO:root:Saving test data in /root/0cc47a3b3d6a.test.json ...
INFO:root:Cleaning up...
Traceback (most recent call last):
  File "bd-performance.py", line 293, in <module>
    test_fio_nbd()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "bd-performance.py", line 44, in test_fio_nbd
    cleanUp(api, nodeIDs, deployInfo)
  File "bd-performance.py", line 119, in cleanUp
    api.nodes.DeleteContainer(testContainer, nodeID)
  File "/usr/local/lib/python3.5/dist-packages/g8os/resourcepool/nodes_service.py", line 247, in DeleteContainer
    return self.client.delete(uri, headers, query_params, content_type)
  File "/usr/local/lib/python3.5/dist-packages/g8os/resourcepool/client.py", line 39, in delete
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.244.188.186:8080/nodes/0cc47a3aad5a/containers/bptest_14952385529563448
```

**Comment by FastGeert** [comment]
Retesting shows the following this stacktrace causes the previous one:
```
[Sun21 07:16] - Job.py              :54  :j.jobcontroller.job.cc91125e06200166a7d5961351e2456e - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/0f3e1a645c4aa29fa0280f95ae21d3ff.py", line 116, in stop
    container.stop()
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/Container.py", line 174, in stop
    self.node.client.container.terminate(self.id)
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 780, in terminate
    result = response.get()
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 132, in get
    raise Timeout()
g8core.client.Timeout
```

**Comment by Dinaamagdy** [comment]
## SV 
verfied in master @ 8c1f6fa4464906fdd071369b967337281a88b9ca
